name: ftw-field-segmentation

channels:
  - conda-forge

dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib
  - geopandas
  - rasterio
  - pyproj
  - scipy
  - shapely
  - scikit-image
  - jupyter